//===============================================
#include "GMimeType.h"
//===============================================
#define GDEFINE_MIMETYPE(x, y)  {true, x, y}
#define GDEFINE_MIMETYPE_LAST   {false, "Unknown", "Unknown"}
//===============================================
GMimeType* GMimeType::m_instance = 0;
//===============================================
GMimeType::sGMimeType MIMETYPE_MAP[] {
        GDEFINE_MIMETYPE("*3gpp", "audio/3gpp"),
        GDEFINE_MIMETYPE("*jpm", "video/jpm"),
        GDEFINE_MIMETYPE("*mp3", "audio/mp3"),
        GDEFINE_MIMETYPE("*rtf", "text/rtf"),
        GDEFINE_MIMETYPE("*wav", "audio/wave"),
        GDEFINE_MIMETYPE("*xml", "text/xml"),
        GDEFINE_MIMETYPE("3g2", "video/3gpp2"),
        GDEFINE_MIMETYPE("3gp", "video/3gpp"),
        GDEFINE_MIMETYPE("3gpp", "video/3gpp"),
        GDEFINE_MIMETYPE("ac", "application/pkix-attr-cert"),
        GDEFINE_MIMETYPE("adp", "audio/adpcm"),
        GDEFINE_MIMETYPE("ai", "application/postscript"),
        GDEFINE_MIMETYPE("apng", "image/apng"),
        GDEFINE_MIMETYPE("appcache", "text/cache-manifest"),
        GDEFINE_MIMETYPE("asc", "application/pgp-signature"),
        GDEFINE_MIMETYPE("atom", "application/atom+xml"),
        GDEFINE_MIMETYPE("atomcat", "application/atomcat+xml"),
        GDEFINE_MIMETYPE("atomsvc", "application/atomsvc+xml"),
        GDEFINE_MIMETYPE("au", "audio/basic"),
        GDEFINE_MIMETYPE("aw", "application/applixware"),
        GDEFINE_MIMETYPE("bdoc", "application/bdoc"),
        GDEFINE_MIMETYPE("bin", "application/octet-stream"),
        GDEFINE_MIMETYPE("bmp", "image/bmp"),
        GDEFINE_MIMETYPE("bpk", "application/octet-stream"),
        GDEFINE_MIMETYPE("buffer", "application/octet-stream"),
        GDEFINE_MIMETYPE("ccxml", "application/ccxml+xml"),
        GDEFINE_MIMETYPE("cdmia", "application/cdmi-capability"),
        GDEFINE_MIMETYPE("cdmic", "application/cdmi-container"),
        GDEFINE_MIMETYPE("cdmid", "application/cdmi-domain"),
        GDEFINE_MIMETYPE("cdmio", "application/cdmi-object"),
        GDEFINE_MIMETYPE("cdmiq", "application/cdmi-queue"),
        GDEFINE_MIMETYPE("cer", "application/pkix-cert"),
        GDEFINE_MIMETYPE("cgm", "image/cgm"),
        GDEFINE_MIMETYPE("class", "application/java-vm"),
        GDEFINE_MIMETYPE("coffee", "text/coffeescript"),
        GDEFINE_MIMETYPE("conf", "text/plain"),
        GDEFINE_MIMETYPE("cpt", "application/mac-compactpro"),
        GDEFINE_MIMETYPE("crl", "application/pkix-crl"),
        GDEFINE_MIMETYPE("css", "text/css"),
        GDEFINE_MIMETYPE("csv", "text/csv"),
        GDEFINE_MIMETYPE("cu", "application/cu-seeme"),
        GDEFINE_MIMETYPE("davmount", "application/davmount+xml"),
        GDEFINE_MIMETYPE("dbk", "application/docbook+xml"),
        GDEFINE_MIMETYPE("deb", "application/octet-stream"),
        GDEFINE_MIMETYPE("def", "text/plain"),
        GDEFINE_MIMETYPE("deploy", "application/octet-stream"),
        GDEFINE_MIMETYPE("disposition-notification", "message/disposition-notification"),
        GDEFINE_MIMETYPE("dist", "application/octet-stream"),
        GDEFINE_MIMETYPE("distz", "application/octet-stream"),
        GDEFINE_MIMETYPE("dll", "application/octet-stream"),
        GDEFINE_MIMETYPE("dmg", "application/octet-stream"),
        GDEFINE_MIMETYPE("dms", "application/octet-stream"),
        GDEFINE_MIMETYPE("doc", "application/msword"),
        GDEFINE_MIMETYPE("dot", "application/msword"),
        GDEFINE_MIMETYPE("drle", "image/dicom-rle"),
        GDEFINE_MIMETYPE("dssc", "application/dssc+der"),
        GDEFINE_MIMETYPE("dtd", "application/xml-dtd"),
        GDEFINE_MIMETYPE("dump", "application/octet-stream"),
        GDEFINE_MIMETYPE("ear", "application/java-archive"),
        GDEFINE_MIMETYPE("ecma", "application/ecmascript"),
        GDEFINE_MIMETYPE("elc", "application/octet-stream"),
        GDEFINE_MIMETYPE("emf", "image/emf"),
        GDEFINE_MIMETYPE("eml", "message/rfc822"),
        GDEFINE_MIMETYPE("emma", "application/emma+xml"),
        GDEFINE_MIMETYPE("eps", "application/postscript"),
        GDEFINE_MIMETYPE("epub", "application/epub+zip"),
        GDEFINE_MIMETYPE("es", "application/ecmascript"),
        GDEFINE_MIMETYPE("exe", "application/octet-stream"),
        GDEFINE_MIMETYPE("exi", "application/exi"),
        GDEFINE_MIMETYPE("exr", "image/aces"),
        GDEFINE_MIMETYPE("ez", "application/andrew-inset"),
        GDEFINE_MIMETYPE("fits", "image/fits"),
        GDEFINE_MIMETYPE("g3", "image/g3fax"),
        GDEFINE_MIMETYPE("gbr", "application/rpki-ghostbusters"),
        GDEFINE_MIMETYPE("geojson", "application/geo+json"),
        GDEFINE_MIMETYPE("gif", "image/gif"),
        GDEFINE_MIMETYPE("glb", "model/gltf-binary"),
        GDEFINE_MIMETYPE("gltf", "model/gltf+json"),
        GDEFINE_MIMETYPE("gml", "application/gml+xml"),
        GDEFINE_MIMETYPE("gpx", "application/gpx+xml"),
        GDEFINE_MIMETYPE("gram", "application/srgs"),
        GDEFINE_MIMETYPE("grxml", "application/srgs+xml"),
        GDEFINE_MIMETYPE("gxf", "application/gxf"),
        GDEFINE_MIMETYPE("gz", "application/gzip"),
        GDEFINE_MIMETYPE("h261", "video/h261"),
        GDEFINE_MIMETYPE("h263", "video/h263"),
        GDEFINE_MIMETYPE("h264", "video/h264"),
        GDEFINE_MIMETYPE("heic", "image/heic"),
        GDEFINE_MIMETYPE("heics", "image/heic-sequence"),
        GDEFINE_MIMETYPE("heif", "image/heif"),
        GDEFINE_MIMETYPE("heifs", "image/heif-sequence"),
        GDEFINE_MIMETYPE("hjson", "application/hjson"),
        GDEFINE_MIMETYPE("hlp", "application/winhlp"),
        GDEFINE_MIMETYPE("hqx", "application/mac-binhex40"),
        GDEFINE_MIMETYPE("htm", "text/html"),
        GDEFINE_MIMETYPE("html", "text/html"),
        GDEFINE_MIMETYPE("ics", "text/calendar"),
        GDEFINE_MIMETYPE("ief", "image/ief"),
        GDEFINE_MIMETYPE("ifb", "text/calendar"),
        GDEFINE_MIMETYPE("iges", "model/iges"),
        GDEFINE_MIMETYPE("igs", "model/iges"),
        GDEFINE_MIMETYPE("img", "application/octet-stream"),
        GDEFINE_MIMETYPE("in", "text/plain"),
        GDEFINE_MIMETYPE("ini", "text/plain"),
        GDEFINE_MIMETYPE("ink", "application/inkml+xml"),
        GDEFINE_MIMETYPE("inkml", "application/inkml+xml"),
        GDEFINE_MIMETYPE("ipfix", "application/ipfix"),
        GDEFINE_MIMETYPE("iso", "application/octet-stream"),
        GDEFINE_MIMETYPE("jade", "text/jade"),
        GDEFINE_MIMETYPE("jar", "application/java-archive"),
        GDEFINE_MIMETYPE("jls", "image/jls"),
        GDEFINE_MIMETYPE("jp2", "image/jp2"),
        GDEFINE_MIMETYPE("jpe", "image/jpeg"),
        GDEFINE_MIMETYPE("jpeg", "image/jpeg"),
        GDEFINE_MIMETYPE("jpf", "image/jpx"),
        GDEFINE_MIMETYPE("jpg", "image/jpeg"),
        GDEFINE_MIMETYPE("jpg2", "image/jp2"),
        GDEFINE_MIMETYPE("jpgm", "video/jpm"),
        GDEFINE_MIMETYPE("jpgv", "video/jpeg"),
        GDEFINE_MIMETYPE("jpm", "image/jpm"),
        GDEFINE_MIMETYPE("jpx", "image/jpx"),
        GDEFINE_MIMETYPE("js", "application/javascript"),
        GDEFINE_MIMETYPE("json", "application/json"),
        GDEFINE_MIMETYPE("json5", "application/json5"),
        GDEFINE_MIMETYPE("jsonld", "application/ld+json"),
        GDEFINE_MIMETYPE("jsonml", "application/jsonml+json"),
        GDEFINE_MIMETYPE("jsx", "text/jsx"),
        GDEFINE_MIMETYPE("kar", "audio/midi"),
        GDEFINE_MIMETYPE("ktx", "image/ktx"),
        GDEFINE_MIMETYPE("less", "text/less"),
        GDEFINE_MIMETYPE("list", "text/plain"),
        GDEFINE_MIMETYPE("litcoffee", "text/coffeescript"),
        GDEFINE_MIMETYPE("log", "text/plain"),
        GDEFINE_MIMETYPE("lostxml", "application/lost+xml"),
        GDEFINE_MIMETYPE("lrf", "application/octet-stream"),
        GDEFINE_MIMETYPE("m1v", "video/mpeg"),
        GDEFINE_MIMETYPE("m21", "application/mp21"),
        GDEFINE_MIMETYPE("m2a", "audio/mpeg"),
        GDEFINE_MIMETYPE("m2v", "video/mpeg"),
        GDEFINE_MIMETYPE("m3a", "audio/mpeg"),
        GDEFINE_MIMETYPE("m4a", "audio/mp4"),
        GDEFINE_MIMETYPE("m4p", "application/mp4"),
        GDEFINE_MIMETYPE("ma", "application/mathematica"),
        GDEFINE_MIMETYPE("mads", "application/mads+xml"),
        GDEFINE_MIMETYPE("man", "text/troff"),
        GDEFINE_MIMETYPE("manifest", "text/cache-manifest"),
        GDEFINE_MIMETYPE("map", "application/json"),
        GDEFINE_MIMETYPE("mar", "application/octet-stream"),
        GDEFINE_MIMETYPE("markdown", "text/markdown"),
        GDEFINE_MIMETYPE("mathml", "application/mathml+xml"),
        GDEFINE_MIMETYPE("mb", "application/mathematica"),
        GDEFINE_MIMETYPE("mbox", "application/mbox"),
        GDEFINE_MIMETYPE("md", "text/markdown"),
        GDEFINE_MIMETYPE("me", "text/troff"),
        GDEFINE_MIMETYPE("mesh", "model/mesh"),
        GDEFINE_MIMETYPE("meta4", "application/metalink4+xml"),
        GDEFINE_MIMETYPE("metalink", "application/metalink+xml"),
        GDEFINE_MIMETYPE("mets", "application/mets+xml"),
        GDEFINE_MIMETYPE("mft", "application/rpki-manifest"),
        GDEFINE_MIMETYPE("mid", "audio/midi"),
        GDEFINE_MIMETYPE("midi", "audio/midi"),
        GDEFINE_MIMETYPE("mime", "message/rfc822"),
        GDEFINE_MIMETYPE("mj2", "video/mj2"),
        GDEFINE_MIMETYPE("mjp2", "video/mj2"),
        GDEFINE_MIMETYPE("mjs", "application/javascript"),
        GDEFINE_MIMETYPE("mml", "text/mathml"),
        GDEFINE_MIMETYPE("mods", "application/mods+xml"),
        GDEFINE_MIMETYPE("mov", "video/quicktime"),
        GDEFINE_MIMETYPE("mp2", "audio/mpeg"),
        GDEFINE_MIMETYPE("mp21", "application/mp21"),
        GDEFINE_MIMETYPE("mp2a", "audio/mpeg"),
        GDEFINE_MIMETYPE("mp3", "audio/mpeg"),
        GDEFINE_MIMETYPE("mp4", "video/mp4"),
        GDEFINE_MIMETYPE("mp4a", "audio/mp4"),
        GDEFINE_MIMETYPE("mp4s", "application/mp4"),
        GDEFINE_MIMETYPE("mp4v", "video/mp4"),
        GDEFINE_MIMETYPE("mpd", "application/dash+xml"),
        GDEFINE_MIMETYPE("mpe", "video/mpeg"),
        GDEFINE_MIMETYPE("mpeg", "video/mpeg"),
        GDEFINE_MIMETYPE("mpg", "video/mpeg"),
        GDEFINE_MIMETYPE("mpg4", "video/mp4"),
        GDEFINE_MIMETYPE("mpga", "audio/mpeg"),
        GDEFINE_MIMETYPE("mrc", "application/marc"),
        GDEFINE_MIMETYPE("mrcx", "application/marcxml+xml"),
        GDEFINE_MIMETYPE("ms", "text/troff"),
        GDEFINE_MIMETYPE("mscml", "application/mediaservercontrol+xml"),
        GDEFINE_MIMETYPE("msh", "model/mesh"),
        GDEFINE_MIMETYPE("msi", "application/octet-stream"),
        GDEFINE_MIMETYPE("msm", "application/octet-stream"),
        GDEFINE_MIMETYPE("msp", "application/octet-stream"),
        GDEFINE_MIMETYPE("mxf", "application/mxf"),
        GDEFINE_MIMETYPE("mxml", "application/xv+xml"),
        GDEFINE_MIMETYPE("n3", "text/n3"),
        GDEFINE_MIMETYPE("nb", "application/mathematica"),
        GDEFINE_MIMETYPE("oda", "application/oda"),
        GDEFINE_MIMETYPE("oga", "audio/ogg"),
        GDEFINE_MIMETYPE("ogg", "audio/ogg"),
        GDEFINE_MIMETYPE("ogv", "video/ogg"),
        GDEFINE_MIMETYPE("ogx", "application/ogg"),
        GDEFINE_MIMETYPE("omdoc", "application/omdoc+xml"),
        GDEFINE_MIMETYPE("onepkg", "application/onenote"),
        GDEFINE_MIMETYPE("onetmp", "application/onenote"),
        GDEFINE_MIMETYPE("onetoc", "application/onenote"),
        GDEFINE_MIMETYPE("onetoc2", "application/onenote"),
        GDEFINE_MIMETYPE("opf", "application/oebps-package+xml"),
        GDEFINE_MIMETYPE("otf", "font/otf"),
        GDEFINE_MIMETYPE("owl", "application/rdf+xml"),
        GDEFINE_MIMETYPE("oxps", "application/oxps"),
        GDEFINE_MIMETYPE("p10", "application/pkcs10"),
        GDEFINE_MIMETYPE("p7c", "application/pkcs7-mime"),
        GDEFINE_MIMETYPE("p7m", "application/pkcs7-mime"),
        GDEFINE_MIMETYPE("p7s", "application/pkcs7-signature"),
        GDEFINE_MIMETYPE("p8", "application/pkcs8"),
        GDEFINE_MIMETYPE("pdf", "application/pdf"),
        GDEFINE_MIMETYPE("pfr", "application/font-tdpfr"),
        GDEFINE_MIMETYPE("pgp", "application/pgp-encrypted"),
        GDEFINE_MIMETYPE("pkg", "application/octet-stream"),
        GDEFINE_MIMETYPE("pki", "application/pkixcmp"),
        GDEFINE_MIMETYPE("pkipath", "application/pkix-pkipath"),
        GDEFINE_MIMETYPE("pls", "application/pls+xml"),
        GDEFINE_MIMETYPE("png", "image/png"),
        GDEFINE_MIMETYPE("prf", "application/pics-rules"),
        GDEFINE_MIMETYPE("ps", "application/postscript"),
        GDEFINE_MIMETYPE("pskcxml", "application/pskc+xml"),
        GDEFINE_MIMETYPE("qt", "video/quicktime"),
        GDEFINE_MIMETYPE("raml", "application/raml+yaml"),
        GDEFINE_MIMETYPE("rdf", "application/rdf+xml"),
        GDEFINE_MIMETYPE("rif", "application/reginfo+xml"),
        GDEFINE_MIMETYPE("rl", "application/resource-lists+xml"),
        GDEFINE_MIMETYPE("rld", "application/resource-lists-diff+xml"),
        GDEFINE_MIMETYPE("rmi", "audio/midi"),
        GDEFINE_MIMETYPE("rnc", "application/relax-ng-compact-syntax"),
        GDEFINE_MIMETYPE("rng", "application/xml"),
        GDEFINE_MIMETYPE("roa", "application/rpki-roa"),
        GDEFINE_MIMETYPE("roff", "text/troff"),
        GDEFINE_MIMETYPE("rq", "application/sparql-query"),
        GDEFINE_MIMETYPE("rs", "application/rls-services+xml"),
        GDEFINE_MIMETYPE("rsd", "application/rsd+xml"),
        GDEFINE_MIMETYPE("rss", "application/rss+xml"),
        GDEFINE_MIMETYPE("rtf", "application/rtf"),
        GDEFINE_MIMETYPE("rtx", "text/richtext"),
        GDEFINE_MIMETYPE("s3m", "audio/s3m"),
        GDEFINE_MIMETYPE("sbml", "application/sbml+xml"),
        GDEFINE_MIMETYPE("scq", "application/scvp-cv-request"),
        GDEFINE_MIMETYPE("scs", "application/scvp-cv-response"),
        GDEFINE_MIMETYPE("sdp", "application/sdp"),
        GDEFINE_MIMETYPE("ser", "application/java-serialized-object"),
        GDEFINE_MIMETYPE("setpay", "application/set-payment-initiation"),
        GDEFINE_MIMETYPE("setreg", "application/set-registration-initiation"),
        GDEFINE_MIMETYPE("sgi", "image/sgi"),
        GDEFINE_MIMETYPE("sgm", "text/sgml"),
        GDEFINE_MIMETYPE("sgml", "text/sgml"),
        GDEFINE_MIMETYPE("shex", "text/shex"),
        GDEFINE_MIMETYPE("shf", "application/shf+xml"),
        GDEFINE_MIMETYPE("shtml", "text/html"),
        GDEFINE_MIMETYPE("sig", "application/pgp-signature"),
        GDEFINE_MIMETYPE("sil", "audio/silk"),
        GDEFINE_MIMETYPE("silo", "model/mesh"),
        GDEFINE_MIMETYPE("slim", "text/slim"),
        GDEFINE_MIMETYPE("slm", "text/slim"),
        GDEFINE_MIMETYPE("smi", "application/smil+xml"),
        GDEFINE_MIMETYPE("smil", "application/smil+xml"),
        GDEFINE_MIMETYPE("snd", "audio/basic"),
        GDEFINE_MIMETYPE("so", "application/octet-stream"),
        GDEFINE_MIMETYPE("spp", "application/scvp-vp-response"),
        GDEFINE_MIMETYPE("spq", "application/scvp-vp-request"),
        GDEFINE_MIMETYPE("spx", "audio/ogg"),
        GDEFINE_MIMETYPE("sru", "application/sru+xml"),
        GDEFINE_MIMETYPE("srx", "application/sparql-results+xml"),
        GDEFINE_MIMETYPE("ssdl", "application/ssdl+xml"),
        GDEFINE_MIMETYPE("ssml", "application/ssml+xml"),
        GDEFINE_MIMETYPE("stk", "application/hyperstudio"),
        GDEFINE_MIMETYPE("styl", "text/stylus"),
        GDEFINE_MIMETYPE("stylus", "text/stylus"),
        GDEFINE_MIMETYPE("svg", "image/svg+xml"),
        GDEFINE_MIMETYPE("svgz", "image/svg+xml"),
        GDEFINE_MIMETYPE("t", "text/troff"),
        GDEFINE_MIMETYPE("t38", "image/t38"),
        GDEFINE_MIMETYPE("tei", "application/tei+xml"),
        GDEFINE_MIMETYPE("teicorpus", "application/tei+xml"),
        GDEFINE_MIMETYPE("text", "text/plain"),
        GDEFINE_MIMETYPE("tfi", "application/thraud+xml"),
        GDEFINE_MIMETYPE("tfx", "image/tiff-fx"),
        GDEFINE_MIMETYPE("tif", "image/tiff"),
        GDEFINE_MIMETYPE("tiff", "image/tiff"),
        GDEFINE_MIMETYPE("tr", "text/troff"),
        GDEFINE_MIMETYPE("ts", "video/mp2t"),
        GDEFINE_MIMETYPE("tsd", "application/timestamped-data"),
        GDEFINE_MIMETYPE("tsv", "text/tab-separated-values"),
        GDEFINE_MIMETYPE("ttc", "font/collection"),
        GDEFINE_MIMETYPE("ttf", "font/ttf"),
        GDEFINE_MIMETYPE("ttl", "text/turtle"),
        GDEFINE_MIMETYPE("txt", "text/plain"),
        GDEFINE_MIMETYPE("u8dsn", "message/global-delivery-status"),
        GDEFINE_MIMETYPE("u8hdr", "message/global-headers"),
        GDEFINE_MIMETYPE("u8mdn", "message/global-disposition-notification"),
        GDEFINE_MIMETYPE("u8msg", "message/global"),
        GDEFINE_MIMETYPE("uri", "text/uri-list"),
        GDEFINE_MIMETYPE("uris", "text/uri-list"),
        GDEFINE_MIMETYPE("urls", "text/uri-list"),
        GDEFINE_MIMETYPE("vcard", "text/vcard"),
        GDEFINE_MIMETYPE("vrml", "model/vrml"),
        GDEFINE_MIMETYPE("vtt", "text/vtt"),
        GDEFINE_MIMETYPE("vxml", "application/voicexml+xml"),
        GDEFINE_MIMETYPE("war", "application/java-archive"),
        GDEFINE_MIMETYPE("wasm", "application/wasm"),
        GDEFINE_MIMETYPE("wav", "audio/wav"),
        GDEFINE_MIMETYPE("weba", "audio/webm"),
        GDEFINE_MIMETYPE("webm", "video/webm"),
        GDEFINE_MIMETYPE("webmanifest", "application/manifest+json"),
        GDEFINE_MIMETYPE("webp", "image/webp"),
        GDEFINE_MIMETYPE("wgt", "application/widget"),
        GDEFINE_MIMETYPE("wmf", "image/wmf"),
        GDEFINE_MIMETYPE("woff", "font/woff"),
        GDEFINE_MIMETYPE("woff2", "font/woff2"),
        GDEFINE_MIMETYPE("wrl", "model/vrml"),
        GDEFINE_MIMETYPE("wsdl", "application/wsdl+xml"),
        GDEFINE_MIMETYPE("wspolicy", "application/wspolicy+xml"),
        GDEFINE_MIMETYPE("x3d", "model/x3d+xml"),
        GDEFINE_MIMETYPE("x3db", "model/x3d+binary"),
        GDEFINE_MIMETYPE("x3dbz", "model/x3d+binary"),
        GDEFINE_MIMETYPE("x3dv", "model/x3d+vrml"),
        GDEFINE_MIMETYPE("x3dvz", "model/x3d+vrml"),
        GDEFINE_MIMETYPE("x3dz", "model/x3d+xml"),
        GDEFINE_MIMETYPE("xaml", "application/xaml+xml"),
        GDEFINE_MIMETYPE("xdf", "application/xcap-diff+xml"),
        GDEFINE_MIMETYPE("xdssc", "application/dssc+xml"),
        GDEFINE_MIMETYPE("xenc", "application/xenc+xml"),
        GDEFINE_MIMETYPE("xer", "application/patch-ops-error+xml"),
        GDEFINE_MIMETYPE("xht", "application/xhtml+xml"),
        GDEFINE_MIMETYPE("xhtml", "application/xhtml+xml"),
        GDEFINE_MIMETYPE("xhvml", "application/xv+xml"),
        GDEFINE_MIMETYPE("xm", "audio/xm"),
        GDEFINE_MIMETYPE("xml", "application/xml"),
        GDEFINE_MIMETYPE("xop", "application/xop+xml"),
        GDEFINE_MIMETYPE("xpl", "application/xproc+xml"),
        GDEFINE_MIMETYPE("xsd", "application/xml"),
        GDEFINE_MIMETYPE("xsl", "application/xml"),
        GDEFINE_MIMETYPE("xslt", "application/xslt+xml"),
        GDEFINE_MIMETYPE("xspf", "application/xspf+xml"),
        GDEFINE_MIMETYPE("xvm", "application/xv+xml"),
        GDEFINE_MIMETYPE("xvml", "application/xv+xml"),
        GDEFINE_MIMETYPE("yaml", "text/yaml"),
        GDEFINE_MIMETYPE("yang", "application/yang"),
        GDEFINE_MIMETYPE("yin", "application/yin+xml"),
        GDEFINE_MIMETYPE("yml", "text/yaml"),
        GDEFINE_MIMETYPE("zip", "application/zip"),
        GDEFINE_MIMETYPE_LAST
};
//===============================================
GMimeType::GMimeType()
: GObject() {

}
//===============================================
GMimeType::~GMimeType() {

}
//===============================================
GMimeType* GMimeType::Instance() {
    if(m_instance == 0) {
        m_instance = new GMimeType;
    }
    return m_instance;
}
//===============================================
GString GMimeType::getMimeType(const GString& _extension) const {
    int i = 0;
    sGMimeType lMimeType;
    GString lExtension = _extension.toLower();
    while(1) {
        lMimeType = MIMETYPE_MAP[i++];
        if(!lMimeType.flag) break;
        if(GString(lMimeType.extension) == lExtension) break;
    }
    if(!lMimeType.flag) {
        slog(eGERR, "Le mimetype recherché n'a pas été trouvé."
                    "|adresse_ip=%s"
                    "|port=%d"
                    "|process=%d"
                    "|extension=%s", m_addressIP.c_str(), m_port, m_pid, _extension.c_str());
    }
    return lMimeType.mimeType;
}
//===============================================
